### ISSUE TITLE
Configuration per environment

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/poucave#162]
Currently, the configuration values can contain environment variables, which are interpolated on startup, for example:

```toml
[checks.remotesettings.changes-timestamps]
description = "Changes are up-to-date"
module = "checks.remotesettings.changes_timestamps"
params.server = "https://settings.${ENV_NAME}.mozaws.net/v1"
```

This is great and useful, we can have one `.toml` config file for our two instances of poucave, without duplicating conf.

However, it's not always that simple. Some URLs are not always so well formed between stage and prod. For example:
* `https://firefox.settings.services.mozilla.com` vs. `https://firefox-settings-attachments-cdn.stage.mozaws.net`
* `https://blocked.cdn.mozilla.net` vs `https://blocked.stage.mozaws.net`
* `wss://push.services.mozilla.com` vs `https://autopush.stage.mozaws.net`

So what can we do? 

### 2. Have templating at deployment level (eg. Ansible)

```
[checks.remotesettings.changes-timestamps]
description = "Changes are up-to-date"
module = "checks.remotesettings.changes_timestamps"
{% if env_name == "stage" %}
params.server = "https://autopush.stage.mozaws.net"
{% else %}
params.server = "wss://push.services.mozilla.com"
{% endif %}
```

### 3. Have templating at poucave level 

Same as above but interpreted by poucave.

### 4. Have conditions on checks

```
[checks.remotesettings.changes-timestamps-stage]
description = "Changes are up-to-date"
module = "checks.remotesettings.changes_timestamps"
params.server = "https://autopush.stage.mozaws.net"
when = "${ENV_NAME} == stage"

[checks.remotesettings.changes-timestamps-prod]
description = "Changes are up-to-date"
module = "checks.remotesettings.changes_timestamps"
params.server = "https://autopush.stage.mozaws.net"
when = "${ENV_NAME} == prod"
```

### 5. Load multiple config files

For example, we would a `common.toml`, and `stage.toml` and `prod.toml`.  *poucave* would load several files instead of one.
